//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS_P.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMS_P.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _125591421_magnifying_glass_on_yellow_background_1255x700 {
            get {
                object obj = ResourceManager.GetObject("125591421-magnifying-glass-on-yellow-background_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _35_351793_credit_or_debit_card_mastercard_logo_visa_card_1_85x50 {
            get {
                object obj = ResourceManager.GetObject("35-351793_credit-or-debit-card-mastercard-logo-visa-card_1_85x50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _35_351793_credit_or_debit_card_mastercard_logo_visa_card_30x30 {
            get {
                object obj = ResourceManager.GetObject("35-351793_credit-or-debit-card-mastercard-logo-visa-card_30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3958_507D7BBF_CD77_1795_DD85_457D088FF32D {
            get {
                object obj = ResourceManager.GetObject("3958_507D7BBF-CD77-1795-DD85-457D088FF32D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3c086f40ad2cf620c3d540da7766b02b {
            get {
                object obj = ResourceManager.GetObject("3c086f40ad2cf620c3d540da7766b02b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _60327636_pastel_watercolor_background_digital_art_painting_ {
            get {
                object obj = ResourceManager.GetObject("60327636-pastel-watercolor-background-digital-art-painting-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _60327636_pastel_watercolor_background_digital_art_painting_1 {
            get {
                object obj = ResourceManager.GetObject("60327636-pastel-watercolor-background-digital-art-painting-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _79fce468980593_5b71946689a07 {
            get {
                object obj = ResourceManager.GetObject("79fce468980593.5b71946689a07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _94_940382_png_50_px_block_user_icon_173x125 {
            get {
                object obj = ResourceManager.GetObject("94-940382_png-50-px-block-user-icon_173x125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a07e8f05a7d516ba7fd90519c5126058 {
            get {
                object obj = ResourceManager.GetObject("a07e8f05a7d516ba7fd90519c5126058", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aed449f3fce390371328c489b93028a6_1255x700 {
            get {
                object obj = ResourceManager.GetObject("aed449f3fce390371328c489b93028a6_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap af8d63a477078732b79ff9d9fc60873f_1255x700 {
            get {
                object obj = ResourceManager.GetObject("af8d63a477078732b79ff9d9fc60873f_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_executive_management_sml_min_1255x700 {
            get {
                object obj = ResourceManager.GetObject("background-executive-management-sml-min_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap candle_colorful_cream_happy_birthday_wallpaper_preview_1255x700 {
            get {
                object obj = ResourceManager.GetObject("candle-colorful-cream-happy-birthday-wallpaper-preview_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cec82d5465d42ae136e627b67dbeb068 {
            get {
                object obj = ResourceManager.GetObject("cec82d5465d42ae136e627b67dbeb068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChicagoFireworks_070420_ColinBoyle_5724 {
            get {
                object obj = ResourceManager.GetObject("ChicagoFireworks-070420-ColinBoyle-5724", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cyan_blue_rays_spiral_sunburst_background_comic_style_1150_39949_1255x700 {
            get {
                object obj = ResourceManager.GetObject("cyan-blue-rays-spiral-sunburst-background-comic-style_1150-39949_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_73441387_stock_photo_black_blank_blackboard_with_hand_1255x700 {
            get {
                object obj = ResourceManager.GetObject("depositphotos_73441387-stock-photo-black-blank-blackboard-with-hand_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_85x50 {
            get {
                object obj = ResourceManager.GetObject("download_85x50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Events_Management_festival_image {
            get {
                object obj = ResourceManager.GetObject("Events Management festival image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f9e9a0f68ff7531459d5b1d0be9733be6924121b_1024_1024_1220x700 {
            get {
                object obj = ResourceManager.GetObject("f9e9a0f68ff7531459d5b1d0be9733be6924121b_1024_1024_1220x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap google_ita_deal_background_forecast_analysis_of_current_situation_1255x700 {
            get {
                object obj = ResourceManager.GetObject("google-ita-deal-background-forecast-analysis-of-current-situation_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_painted_watercolor_background_with_sky_clouds_shape_24972_1095 {
            get {
                object obj = ResourceManager.GetObject("hand-painted-watercolor-background-with-sky-clouds-shape_24972-1095", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images_382x533 {
            get {
                object obj = ResourceManager.GetObject("images_382x533", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1049658692_612x612_1255x700 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1049658692-612x612_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1069160140_612x612_1255x700 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1069160140-612x612_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1226478926_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1226478926-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_856607846_1024x1024_1255x700 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-856607846-1024x1024_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_918958976_612x612_1255x700 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-918958976-612x612_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lights_background_1200x650 {
            get {
                object obj = ResourceManager.GetObject("lights-background_1200x650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_1469371670807_013ccf25f16a {
            get {
                object obj = ResourceManager.GetObject("photo-1469371670807-013ccf25f16a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_1505236858219_8359eb29e329_1255x700 {
            get {
                object obj = ResourceManager.GetObject("photo-1505236858219-8359eb29e329_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_1523050854058_8df90110c9f1_1255x700 {
            get {
                object obj = ResourceManager.GetObject("photo-1523050854058-8df90110c9f1_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_1610374792793_f016b77ca51a {
            get {
                object obj = ResourceManager.GetObject("photo-1610374792793-f016b77ca51a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_1617954096030_d8c4c47f2a99 {
            get {
                object obj = ResourceManager.GetObject("photo-1617954096030-d8c4c47f2a99", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_modern_double_color_futuristic_neon_background_image_351866_1_1255x700 {
            get {
                object obj = ResourceManager.GetObject("pngtree-modern-double-color-futuristic-neon-background-image_351866_1_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_modern_double_color_futuristic_neon_background_image_351866_1_1255x7001 {
            get {
                object obj = ResourceManager.GetObject("pngtree-modern-double-color-futuristic-neon-background-image_351866_1_1255x7001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_orange_gold_autumn_october_thanksgiving_feedback_background_image_267032_1255x700 {
            get {
                object obj = ResourceManager.GetObject("pngtree-orange-gold-autumn-october-thanksgiving-feedback-background-image_267032_" +
                        "1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap v462_n_130_textureidea_1_1255x700 {
            get {
                object obj = ResourceManager.GetObject("v462-n-130-textureidea_1_1255x700", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap v462_n_130_textureidea_1_1255x7001 {
            get {
                object obj = ResourceManager.GetObject("v462-n-130-textureidea_1_1255x7001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap v462_n_130_textureidea_1_1255x7002 {
            get {
                object obj = ResourceManager.GetObject("v462-n-130-textureidea_1_1255x7002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap v462_n_130_textureidea_1_1255x7003 {
            get {
                object obj = ResourceManager.GetObject("v462-n-130-textureidea_1_1255x7003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap v462_n_130_textureidea_1_1255x7004 {
            get {
                object obj = ResourceManager.GetObject("v462-n-130-textureidea_1_1255x7004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap v462_n_130_textureidea_1_1255x7005 {
            get {
                object obj = ResourceManager.GetObject("v462-n-130-textureidea_1_1255x7005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
